### ISSUE TITLE
Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by pratikt-cuelogic** [howtographql/react-apollo#32]
not sure something went wrong at initial installation or not..
however im not able to move ahead with any query...
only following error is being display

> Unexpected token I in JSON at position 0
![playground http localhost 4000 _02](https://user-images.githubusercontent.com/6252256/36837823-67e41a0c-1d63-11e8-9a5b-f13395a91fb5.png)
![playground http localhost 4000 _01](https://user-images.githubusercontent.com/6252256/36837824-681fcf84-1d63-11e8-9298-d32679e45b06.png)

fyI: I was following steps provided at https://www.howtographql.com/react-apollo/0-introduction/

**Comment by mhesham32** [comment]
+1

**Comment by danielsbird** [comment]
I had a similar error: `Unexpected token < in JSON at position 0`. I solved it by uninstalling yarn, reinstalling yarn, deleting the `node_modules` directory in this project, and then running `yarn install`. 

I got the idea from [this comment](https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-368451251) in the graphql-yoga repo but I don't yet understand why upgrading yarn fixed the error. Before upgrading yarn I was using yarn 1.1.0 and now I am using yarn 1.5.1.

**Comment by ggomersall** [comment]
Does anyone else know why this error is happening?

doesn't really make sense

**Comment by IevgenRagulin** [comment]
Getting error "Unexpected token P in JSON at position 0" (I'm using a different setup, but I'm also using Apollo and Graphql playground". Interestingly, when I copy curl from playground, the request executes successfully. It must be some Grapqhl Playground issue

**Comment by swcarlosrj** [comment]
Thanks @pratikt-cuelogic for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!

**Comment by KumarAbhirup** [comment]
Hey, I'm still getting this problem. 
`Network error: Unexpected token N in JSON at position 0`
