### ISSUE TITLE
Error: "Ensure there is only one instance of GraphQL in the node_modules directory"

### ISSUE THREAD

**Issue by morganpierson** [howtographql/react-apollo#33]
Whenever I try to run the query to see the two links I create at the beginning of the tutorial I receive this error:  "message": "Cannot use GraphQLNonNull \"[Link]!\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.

I have made sure I do not have duplicate versions of graphql in my node_modules, and I have even tried to roll back to an earlier version of graphql, but the error persists. Any help or advice is greatly appreciated

**Comment by seanyboy49** [comment]
Had this error too. Try updating your dependencies against the graphcool package.json and restarting your server. Worked for me! 

https://github.com/graphcool/graphql-server-example/blob/master/package.json

**Comment by morganpierson** [comment]
@seanyboy49 Thank you!!!!!!! How did you come across this solution?

**Comment by marktani** [comment]
Thanks for chiming in, @seanyboy49! 🙂 
I described the solution here: https://stackoverflow.com/a/49116060/1176596.

Could you provide a PR with a working setup?

**Comment by marktani** [comment]
Fixed in https://github.com/howtographql/react-apollo/commit/a3a9b7f115ba71fb2b6900ec31314e9657df5e61

**Comment by erchaves** [comment]
In case this helps anyone, I was still getting this `Duplicate "graphql" modules` error while trying to run a production build if my NODE_ENV was set to 'development' by accident. I fixed it by setting my NODE_ENV to 'production' or clearing it to nothing. I'm not sure why NODE_ENV=development caused this error, but that was my easy fix.

**Comment by lukebarnard1** [comment]
I just experienced this FTR:
```
$ prisma deploy
Warning: Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version.
  
Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v10.15.3
Prisma server version: 1.32.0-beta
  
For further information, please read: http://bit.ly/prisma-cli-server-sync
  
Deploying service `[...]` to stage `[...]` to server `prisma-eu1` 375ms
Service is already up to date.

post-deploy:
 ▸    Cannot use GraphQLNonNull "LinkWhereUniqueInput!" from another module or
 ▸    realm.
```

I noticed the version of graphql in the root level `yarn.lock` was different to the one in `server` (only a minor version difference).

Solution was to remove the `server/yarn.lock` and `yarn install` in `server`.

**Comment by ellieseoejung** [comment]
> I just experienced this FTR:
> 
> ```
> $ prisma deploy
> Warning: Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version.
>   
> Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v10.15.3
> Prisma server version: 1.32.0-beta
>   
> For further information, please read: http://bit.ly/prisma-cli-server-sync
>   
> Deploying service `[...]` to stage `[...]` to server `prisma-eu1` 375ms
> Service is already up to date.
> 
> post-deploy:
>  ▸    Cannot use GraphQLNonNull "LinkWhereUniqueInput!" from another module or
>  ▸    realm.
> ```
> 
> I noticed the version of graphql in the root level `yarn.lock` was different to the one in `server` (only a minor version difference).
> 
> Solution was to remove the `server/yarn.lock` and `yarn install` in `server`.

This solved it for me! :D

**Comment by kvr2277** [comment]
Google got me here for issue 

> "Ensure that there is only one instance of \"graphql\" in the node_modules\ndirectory" 

- I'm using npm. Removed package-lock.json, node_modules and have put 

```
"resolutions": {
    "graphql": "^0.13.0"
  }
```

which fixed the issue

**Comment by magicdustin** [comment]
> Google got me here for issue
> 
> > "Ensure that there is only one instance of "graphql" in the node_modules\ndirectory"
> 
> * I'm using npm. Removed package-lock.json, node_modules and have put
> 
> ```
> "resolutions": {
>     "graphql": "^0.13.0"
>   }
> ```
> 
> which fixed the issue

This fixed it for me!

**Comment by elafifi** [comment]
> Google got me here for issue
> 
> > "Ensure that there is only one instance of "graphql" in the node_modules\ndirectory"
> 
> * I'm using npm. Removed package-lock.json, node_modules and have put
> 
> ```
> "resolutions": {
>     "graphql": "^0.13.0"
>   }
> ```
> 
> which fixed the issue

this fixed problem with me great thanks

**Comment by fdev** [comment]
Google got me here as well.

Using `npm-force-resolutions` did not work for me. Even with the exact same version of `graphql` as multiple (sub)dependencies, the error would still show.

What _did_ fix it for me was using `npm dedupe`. Hope this helps the next person who finds this thread.

**Comment by SidKhanna296** [comment]
for anyone in the future - I was still having these issues - I had upgraded a library that uses graphql to the same version as my service and it was still throwing this error - I was using `npm link` to refer to my library where I had made said changes

it seems graphql does not play well with npm link - a solution is to use `npm pack` on the library you're making changes and then just install the tarball you get in your service to test your changes - its not ideal but it may help

**Comment by babkenmes** [comment]
for anyone in the future 2 - in case you are using Visual Studio just close it when you run the script

**Comment by HassanBahati** [comment]
> for anyone in the future 2 - in case if you are using Visual Studio just close it when you run the script

I really agree...

**Comment by ThallesP** [comment]
i had this problem when using `tsup` as a build tool, after migrating back to `tsc` it worked.

Just saying in here becase this is the first result when you search for the error.
