### ISSUE TITLE
error after vote in /search

### ISSUE THREAD

**Issue by diogoalves** [howtographql/react-apollo#6]
In /search route 
when click in vote button we get 
```
TypeError: _this.props.updateStoreAfterVote is not a function
...  
```

Seach component is not passing updateStoreAfterVote to Links component.

**Comment by nikolasburk** [comment]
Hi @diogoalves, thanks so much for pointing this out and my sincere apologies for the delay! This issue was fixed with the latest update to the tutorial.  Please let me know if you're running into any further issues 🙂

**Comment by againksy** [comment]
@nikolasburk this does not fixed not in this repo not in the tutorial. still no updateStoreAfterVote passed to the <Link> from <Search>
